"""init

Revision ID: c941a4998a67
Revises: 
Create Date: 2024-02-29 23:30:55.246386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c941a4998a67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column1', sa.String(), nullable=True),
    sa.Column('column2', sa.Text(), nullable=True),
    sa.Column('column3', sa.Boolean(), nullable=True),
    sa.Column('column4', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rows_column1'), 'rows', ['column1'], unique=True)
    op.create_index(op.f('ix_rows_id'), 'rows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rows_id'), table_name='rows')
    op.drop_index(op.f('ix_rows_column1'), table_name='rows')
    op.drop_table('rows')
    # ### end Alembic commands ###
